name: Release Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  tag-and-build:
    name: Tag, Build, and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get version from pom.xml
        id: get_version
        run: |
          VERSION=$(grep -m 1 '<version>' pom.xml | sed -E 's/.*<version>([^<]+)<\/version>.*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get short commit SHA
        id: get_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create tag and push
        run: |
          TAG="${VERSION}-${SHORT_SHA}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG

  build-and-release:
    name: Build JAR and Create Release
    runs-on: ubuntu-latest
    needs: tag-and-build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew bootJar

      - name: Parse version and SHA from tag
        id: parse_tag
        run: |
          FULL_TAG=${GITHUB_REF#refs/tags/}
          VERSION=${FULL_TAG%-*}
          SHA=${FULL_TAG##*-}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SHA=$SHA" >> $GITHUB_ENV

      - name: Rename JAR
        run: |
          cd build/libs/
          mv *.jar CoreProtect-${VERSION}-${SHA}.jar

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: coreprotect-jar
          path: build/libs/CoreProtect-*.jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/CoreProtect-*.jar
          name: CoreProtect-${{ env.VERSION }}-${{ env.SHA }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
